# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='\u65b0\u95fb', max_length=100)),
                ('datetime', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('S', 'Single'), ('M', 'Multiple')], default='S', max_length=2)),
                ('choices', models.ManyToManyField(related_name='_question_choices_+', to='base.Choice')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='\u6e38\u5ba2', max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='\u65b0\u95fb', max_length=100)),
                ('datetime', models.DateTimeField()),
                ('content', models.TextField()),
                ('questions', models.ManyToManyField(related_name='_vote_questions_+', to='base.Question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(related_name='_question_votes_+', to='base.Vote'),
        ),
        migrations.AddField(
            model_name='choice',
            name='questions',
            field=models.ManyToManyField(related_name='_choice_questions_+', to='base.Question'),
        ),
    ]
