# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='questions',
            field=models.ManyToManyField(null=True, related_name='_choice_questions_+', to='base.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(null=True, related_name='_question_choices_+', to='base.Choice'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='questions',
            field=models.ManyToManyField(null=True, related_name='_vote_questions_+', to='base.Question'),
        ),
    ]
